// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pejjiempprraabupzjgd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBlamppZW1wcHJyYWFidXB6amdkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwODQ0NzIsImV4cCI6MjA3MDY2MDQ3Mn0.PRD2avKRVP0nowtPqfH-dkaP71uvtJgduIaUd5iI03A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});